codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%

  # Frontend coverage
  frontend:
    target: 60%
    threshold: 1%
    paths:
      - "frontend/src/**"

  # Backend coverage
  backend:
    target: 55%
    threshold: 1%
    paths:
      - "backend/services/**"
      - "backend/utils/**"
      - "backend/app.py"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "frontend/node_modules"
  - "frontend/dist"
  - "frontend/__tests__"
  - "frontend/**/*.config.*"
  - "backend/tests"
  - "backend/**/__pycache__"
  - "backend/venv"
  - "backend/.venv"

flags:
  frontend:
    paths:
      - frontend/src
    carryforward: true

  backend:
    paths:
      - backend/services
      - backend/utils
      - backend/app.py
    carryforward: true
